WatsonTruckV2/Models/Life_Insurance.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatsonTruckV2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Life_Insurance
    {
        public int LifeInsurance_id { get; set; }
        public int Employee_id { get; set; }
        public string GroupPlanNumber { get; set; }
        public Nullable<System.DateTime> BenefitsEffectiveDate { get; set; }
        public string InitialEnrollment { get; set; }
        public string ReEnrollment { get; set; }
        public string AddEmployeeAndDependents { get; set; }
        public string DropRefuseCoverage { get; set; }
        public string InformationChange { get; set; }
        public string IncreaseAmount { get; set; }
        public string FamilyStatusChange { get; set; }
        public string MarriedOrHaveSpouse { get; set; }
        public string HaveChildrenOrHaveDependents { get; set; }
        public Nullable<System.DateTime> DateOfMarriage { get; set; }
        public Nullable<System.DateTime> PlacementDateOfAdoptedChild { get; set; }
        public string AddDependent { get; set; }
        public string DropDependent { get; set; }
        public string DropEmployee { get; set; }
        public string DropDependents { get; set; }
        public Nullable<System.DateTime> LastDayOfCoverage { get; set; }
        public string Retirement { get; set; }
        public Nullable<System.DateTime> LastDayWorked { get; set; }
        public string OtherEvent { get; set; }
        public string OtherEventReason { get; set; }
        public Nullable<System.DateTime> OtherEventDate { get; set; }
        public string EmployeeDentalDrop { get; set; }
        public string SpouseDentalDrop { get; set; }
        public string DependentDentalDrop { get; set; }
        public string EmployeeVisionDrop { get; set; }
        public string SpouseVisionDrop { get; set; }
        public string DependentVisionDrop { get; set; }
        public string DropBasicLife { get; set; }
        public string DropDental { get; set; }
        public string DropVision { get; set; }
        public string Divorce { get; set; }
        public Nullable<System.DateTime> DivorceDate { get; set; }
        public string DeathOfSpouse { get; set; }
        public Nullable<System.DateTime> DeathOfSpouseDate { get; set; }
        public string TerminationOrExpirationOfCoverage { get; set; }
        public Nullable<System.DateTime> TerminationOrExpirationOfCoverageDate { get; set; }
        public string DentalCoverageLost { get; set; }
        public string VisionCoverageLost { get; set; }
        public string CoveredUnderOtherInsurance { get; set; }
        public string DoNotWantDentalCoverage { get; set; }
        public string EmployeeCoveredUnderOtherDentalPlan { get; set; }
        public string SpouseCoveredUnderOtherDentalPlan { get; set; }
        public string DependentsCoveredUnderOtherDentalPlan { get; set; }
        public string DoNotWantVisionCoverage { get; set; }
        public string EmployeeCoveredUnderOtherVisionPlan { get; set; }
        public string SpouseCoveredUnderOtherVisionPlan { get; set; }
        public string DependentsCoveredUnderOtherVisionPlan { get; set; }
        public string OwnerBasicLifeWithADandDPolicyAmount { get; set; }
        public string ManagerBasicLifeWithADandDPolicyAmount { get; set; }
        public string EmployeeBasicLifeWithADandDPolicyAmount { get; set; }
        public string SpouseBasicLifeWithADandDPolicyAmount { get; set; }
        public string DoNotWantBasicLifeCoverageWithADandD { get; set; }
        public string AmountOfPreviousPolicy { get; set; }
        public string EmployeeSignature { get; set; }
        public Nullable<System.DateTime> EmployeeSignatureDate { get; set; }
        public string SubTotalCode { get; set; }
        public string TerminationEmploymentOfDropCoverage { get; set; }
        public Nullable<System.DateTime> TerminationEmploymentDateOfDropCoverage { get; set; }
        public string TerminationEmploymentLossOfOtherCoverage { get; set; }
        public Nullable<System.DateTime> TerminationEmploymentDateLossOfOtherCoverage { get; set; }
        public string Other { get; set; }
        public string OtherReason { get; set; }
        public string DentalCoverage { get; set; }
        public string VisionCoverage { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

WatsonTruckV2/Controllers/Life_InsuranceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
//using SelectPdf;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Text;
using System.Dynamic;
using System.Data;
using System.Configuration;
using System.Data.SqlClient;
using System.Net.Http;
using System.Web.Http;
using System.Web.Mvc;
using WatsonTruckV2.Models;


namespace WatsonTruckV2.Controllers
{
    //[System.Web.Mvc.Authorize = "Employee, Manager"]
    //[Authorize(Roles = "Employee, Manager")]
    public class Life_InsuranceController : Controller
    {
        private WatsonTruckEntities db = new WatsonTruckEntities();

        private static Group_Health grpHealth = new Group_Health();
        private static Employee employee = new Employee();
        private static List<Family_Info> family = new List<Family_Info>();
        private static Life_Insurance lifeIns = new Life_Insurance();

        public ActionResult LifeInsuranceEnrollment(int? LifeInsurance_id, int? Employee_id, int? Beneficiary_id, string Message)
        {
            ViewBag.LifeInsurance_id = LifeInsurance_id;
            ViewBag.Employee_id = Employee_id;
            ViewBag.Beneficiary_id = Beneficiary_id;
            ViewBag.Message = Message;


            EmployeeAndInsuranceVM empAndInsVM = new EmployeeAndInsuranceVM();

            empAndInsVM.employee = db.Employees.FirstOrDefault(i => i.Employee_id == Employee_id);
            empAndInsVM.lifeIns = db.Life_Insurance.FirstOrDefault(i => i.Employee_id == Employee_id);
            empAndInsVM.benefiList = db.Beneficiaries.Where(i => i.Employee_id == Employee_id).ToList();

            empAndInsVM.spouse = db.Family_Info.FirstOrDefault(i => i.Employee_id == Employee_id && i.RelationshipToInsured == "Spouse");
            empAndInsVM.family = db.Family_Info.Where(i => i.Employee_id == Employee_id && i.RelationshipToInsured != "Spouse").ToList();
            if (empAndInsVM.spouse != null)
            {
                empAndInsVM.spouse = db.Family_Info.FirstOrDefault(i => i.Employee_id == Employee_id && i.FamilyMember_id == empAndInsVM.spouse.FamilyMember_id);
                empAndInsVM.family = db.Family_Info.Where(i => i.Employee_id == Employee_id && i.FamilyMember_id != empAndInsVM.spouse.FamilyMember_id).ToList();
            }
            else
            {
                empAndInsVM.spouse = null;
                empAndInsVM.family = db.Family_Info.Where(i => i.Employee_id == Employee_id).ToList();
            }

            return View(empAndInsVM);
        }

        //Create-LifeIns
        public JsonResult LifeInsEnrollmentNew(int Employee_id, string GroupPlanNumber, DateTime? BenefitsEffectiveDate, string InitialEnrollment, string ReEnrollment,
            string AddEmployeeAndDependents, string DropRefuseCoverage, string InformationChange, string IncreaseAmount, string FamilyStatusChange, string SubTotalCode,
            string Married, DateTime? DateOfMarriage, string OtherDependents, DateTime? DateOfAdoption, /*string AddDep, string DropDep,*/ string AddDropDep, string DropEmployee,
            string DropDependents, DateTime? LastDayOfCoverage, string TerminationEmploymentOfDropCoverage, string Retirement, DateTime? LastDayWorked, string OtherEvent,
            string OtherEventReason, DateTime? OtherEventDate, string DropBasicLife, string EmployeeDentalDrop, string SpouseDentalDrop, string DependentDentalDrop,
            string EmployeeVisionDrop, string SpouseVisionDrop, string DependentVisionDrop, string TerminationEmploymentLossOfOtherCoverage,
            DateTime? TerminationEmploymentDateLossOfOtherCoverage, string Divorce, DateTime? DivorceDate, string DeathOfSpouse, DateTime? DeathOfSpouseDate,
            string TerminationOrExpirationOfCoverage, DateTime? TerminationOrExpirationOfCoverageDate, string DentalCoverageLost, string VisionCoverageLost,
            string CoveredUnderOtherInsurance, string Other, string OtherReason, string DoNotWantDentalCoverage, string EmployeeCoveredUnderOtherDental,
            string SpouseCoveredUnderOtherDental, string DependentsCoveredUnderOtherDental, string DoNotWantVisionCoverage, string EmployeeCoveredUnderOtherVision,
            string SpouseCoveredUnderOtherVision, string DependentsCoveredUnderOtherVision, string PrimaryBeneficiary, string ContingentBeneficiary,
            string OwnerBasicLifeADandDPolicyAmount, string ManagerBasicLifeADandDPolicyAmount, string EmployeeBasicLifeADandDPolicyAmount,
            string DoNotWantBasicLifeCoverageADandD, string PreviousPolicyAmount, string DentalPlan, string VisionPlan, string EmployeeSignature,
            DateTime? EmployeeSignatureDate)
        {
            string response = "";

            int record = (from life in db.Life_Insurance
                          where life.Employee_id == Employee_id
                          select life).Count();

            if (record > 0)
            {
                response = "Record already exists.";

            }
            else
            {

                Life_Insurance lifeIns = new Life_Insurance();

                lifeIns.Employee_id = Employee_id;
                lifeIns.GroupPlanNumber = GroupPlanNumber;
                lifeIns.BenefitsEffectiveDate = BenefitsEffectiveDate;
                lifeIns.InitialEnrollment = InitialEnrollment;
                lifeIns.ReEnrollment = ReEnrollment;
                lifeIns.AddEmployeeAndDependents = AddEmployeeAndDependents;
                lifeIns.DropRefuseCoverage = DropRefuseCoverage;
                lifeIns.InformationChange = InformationChange;
                lifeIns.IncreaseAmount = IncreaseAmount;
                lifeIns.FamilyStatusChange = FamilyStatusChange;
                lifeIns.SubTotalCode = SubTotalCode;
                lifeIns.MarriedOrHaveSpouse = Married;
                lifeIns.DateOfMarriage = DateOfMarriage;
                lifeIns.HaveChildrenOrHaveDependents = OtherDependents;
                lifeIns.PlacementDateOfAdoptedChild = DateOfAdoption;
                //lifeIns.AddDependent = AddDep;
                //lifeIns.DropDependent = DropDep;
                lifeIns.DropEmployee = DropEmployee;
                lifeIns.DropDependents = DropDependents;
                lifeIns.LastDayOfCoverage = LastDayOfCoverage;
                lifeIns.TerminationEmploymentOfDropCoverage = TerminationEmploymentOfDropCoverage;
                lifeIns.Retirement = Retirement;
                lifeIns.LastDayWorked = LastDayWorked;
                lifeIns.OtherEvent = OtherEvent;
                lifeIns.OtherEventReason = OtherEventReason;
                lifeIns.OtherEventDate = OtherEventDate;
                lifeIns.DropBasicLife = DropBasicLife;
                lifeIns.EmployeeDentalDrop = EmployeeDentalDrop;
                lifeIns.SpouseDentalDrop = SpouseDentalDrop;
                lifeIns.DependentDentalDrop = DependentDentalDrop;
                lifeIns.EmployeeVisionDrop = EmployeeVisionDrop;
                lifeIns.SpouseVisionDrop = SpouseVisionDrop;
                lifeIns.DependentVisionDrop = DependentVisionDrop;
                lifeIns.TerminationEmploymentLossOfOtherCoverage = TerminationEmploymentLossOfOtherCoverage;
                lifeIns.TerminationEmploymentDateLossOfOtherCoverage = TerminationEmploymentDateLossOfOtherCoverage;
                lifeIns.Divorce = Divorce;
                lifeIns.DivorceDate = DivorceDate;
                lifeIns.DeathOfSpouse = DeathOfSpouse;
                lifeIns.DeathOfSpouseDate = DeathOfSpouseDate;
                lifeIns.TerminationOrExpirationOfCoverage = TerminationOrExpirationOfCoverage;
                lifeIns.TerminationOrExpirationOfCoverageDate = TerminationOrExpirationOfCoverageDate;
                lifeIns.DentalCoverageLost = DentalCoverageLost;
                lifeIns.VisionCoverageLost = VisionCoverageLost;
                lifeIns.CoveredUnderOtherInsurance = CoveredUnderOtherInsurance;
                lifeIns.Other = Other;
                lifeIns.OtherReason = OtherReason;

                lifeIns.DentalCoverage = DentalPlan;
                lifeIns.VisionCoverage = VisionPlan;

                lifeIns.DoNotWantDentalCoverage = DoNotWantDentalCoverage;
                lifeIns.EmployeeCoveredUnderOtherDentalPlan = EmployeeCoveredUnderOtherDental;
                lifeIns.SpouseCoveredUnderOtherDentalPlan = SpouseCoveredUnderOtherDental;
                lifeIns.DependentsCoveredUnderOtherDentalPlan = DependentsCoveredUnderOtherDental;

                lifeIns.DoNotWantVisionCoverage = DoNotWantVisionCoverage;
                lifeIns.EmployeeCoveredUnderOtherVisionPlan = EmployeeCoveredUnderOtherVision;
                lifeIns.SpouseCoveredUnderOtherVisionPlan = SpouseCoveredUnderOtherVision;
                lifeIns.DependentsCoveredUnderOtherVisionPlan = DependentsCoveredUnderOtherVision;
                lifeIns.OwnerBasicLifeWithADandDPolicyAmount = OwnerBasicLifeADandDPolicyAmount;
                lifeIns.ManagerBasicLifeWithADandDPolicyAmount = ManagerBasicLifeADandDPolicyAmount;
                lifeIns.EmployeeBasicLifeWithADandDPolicyAmount = EmployeeBasicLifeADandDPolicyAmount;
                lifeIns.DoNotWantBasicLifeCoverageWithADandD = DoNotWantBasicLifeCoverageADandD;
                lifeIns.AmountOfPreviousPolicy = PreviousPolicyAmount;
                lifeIns.EmployeeSignature = EmployeeSignature;
                lifeIns.EmployeeSignatureDate = EmployeeSignatureDate;

                db.Life_Insurance.Add(lifeIns);

                db.SaveChanges();
            }

            int result = Employee_id;


            return Json(new { data = result, error = response }, JsonRequestBehavior.AllowGet);
        }

        //----------------------------------------------------------------------------------------

        //Edit-LifeIns

WatsonTruckV2/Views/Life_Insurance/AddBeneficiary.cshtml
@model WatsonTruckV2.Models.EmployeeAndInsuranceVM

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>Add Beneficiary</title>
</head>
<body>
    <input type="hidden" id="Employee_id" class="form-control" name="Employee_id" value="@ViewBag.Employee_id" />
    <div class="collapsible" id="BeneficiaryEnrollment">Add Beneficiary</div>
    <div class="content">
        <div id="divBeneficiaryInfo">
            <div class="form-group">
                <table class="table table-condensed">
                    <tr>
                        <td>
                            <input type="checkbox" class="checkbox-inline" id="PrimaryBeneficiary" name="PrimaryBeneficiary" value="" /><label for="Primary">Primary</label>
                            <input type="checkbox" class="checkbox-inline" id="ContingentBeneficiary" name="ContingentBeneficiary" value="" /><label for="Contingent">Contingent</label>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <input type="text" id="FirstName" class="form-control" name="FirstName" placeholder="First Name" value="" />
                        </td>
                        <td>
                            <input type="text" id="LastName" class="form-control" name="LastName" placeholder="Last Name" value="" />
                        </td>
                        <td>
                            <input type="text" id="SSN" class="form-control" name="SSN" placeholder="SSN" value="" />
                        </td>
                        <td>
                            <input type="text" id="RelationshipToEmployee" class="form-control" name="RelationshipToEmployee" placeholder="Relationship to Employee" value="" />
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <label style="display:table-cell">Date of Birth:</label>
                            <input type="date" id="DOB" class="form-control" name="DOB" value="" />
                        </td>
                        <td>
                            <label style="display:table-cell">Phone Number:</label>
                            <input type="text" id="PhoneNumber" class="form-control" name="PhoneNumber" placeholder="" value="" />
                        </td>
                        <td>
                            <label style="display:table-cell">Percentage Of Benefits:</label>
                            <input type="number" id="PercentageOfBenefits" class="form-control" name="PercentageOfBenefits" placeholder="" value="" />
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <input type="text" id="MailingAddress" class="form-control" name="Address" placeholder="Mailing Address" value="" />
                        </td>
                        <td>
                            <input type="text" id="City" class="form-control" name="City" placeholder="City" value="" />
                        </td>
                        <td>
                            <input type="text" id="State" class="form-control" name="State" placeholder="State" value="" />
                        </td>
                        <td>
                            <input type="text" id="ZipCode" class="form-control" name="ZipCode" placeholder="Zip Code" value="" />
                        </td>
                    </tr>

                </table>
                <div class="form-group">
                    <div class="col-md-offset-11">
                        <button type="submit" id="submitBeneficiary" class="btn">Save</button>
                    </div>
                </div>
                <p>
                    @Html.ActionLink("Back to Life Insurance", "LifeInsuranceEnrollment", "Life_Insurance", new { Employee_id = ViewBag.Employee_id }, null)
                </p>
            </div>
        </div>
    </div>


</body>
</html>

<style>
    .collapsible {
        background-color: #2e4593;
        color: white;
        cursor: pointer;
        padding: 18px;
        width: 100%;
        border: none;
        text-align: center;
        outline: none;
        font-size: 15px;
    }

        .active, .collapsible:hover {
            background-color: #2e4593;
        }

    .content {
        padding: 0 10px;
        display: none;
        overflow: hidden;
        background-color: #f1f1f1;
    }

    .button {
        text-align: right;
    }

    .btn:hover {
        background-color: #2e4593;
        color: white;
    }

    a {
        text-decoration: none;
        display: inline-flex;
        padding: 8px 8px;
    }
</style>

<script>
    var col = document.querySelectorAll(".collapsible");
    var i;

    var Employee_id;

    for (i = 0; i < col.length; i++) {
        col[i].addEventListener("click", function () {
            this.classList.toggle("active");
            var content = this.nextElementSibling;
            if (content.style.display === "block") {
                content.style.display = "none";
            } else {
                content.style.display = "block";
            }

        });
    }

    $(document).ready(function () {
        $('.radio-inline').click(function () {
            $('.radio-inline').not(this).prop('checked', false);
        });
    });



    document.querySelector("#submitBeneficiary").addEventListener("click", function () {

        var message;
        alert = confirm("Beneificiary information has been saved. Thank you!")

        if (alert == true) {
            message = "Please proceed to Life Insurance edit page to review information. Thank you!!";
            var alert = confirm(message)
            if (alert == true) {

                window.location.href = "/Life_Insurance/EditLifeInsurance/?Employee_id=" + @ViewBag.Employee_id;

            }
            else {
                window.location.href = "/Employee/EmpOverview/?Employee_id=" + @ViewBag.Employee_id;
            }
        }
        else {
            if (alert == false) {

                window.location.href = "/Employee/EmpOverview/?Employee_id=" + @ViewBag.Employee_id;
            }
        }
    })

    document.addEventListener("DOMContentLoaded", function () {
        document.querySelector("#submitBeneficiary").addEventListener("click", function () {
            Employee_id = document.getElementById("Employee_id").value;
            PrimaryBeneficiary = document.getElementById("PrimaryBeneficiary").checked;
            ContingentBeneficiary = document.getElementById("ContingentBeneficiary").checked;
            RelationshipToEmployee = document.getElementById("RelationshipToEmployee").value;
            SSN = document.getElementById("SSN").value;
            FirstName = document.getElementById("FirstName").value;
            LastName = document.getElementById("LastName").value;
            DateOfBirth = document.getElementById("DOB").value;
            PhoneNumber = document.getElementById("PhoneNumber").value;
            PercentageOfBenefits = document.getElementById("PercentageOfBenefits").value;
            MailingAddress = document.getElementById("MailingAddress").value;
            City = document.getElementById("City").value;
            State = document.getElementById("State").value;
            ZipCode = document.getElementById("ZipCode").value;

            var data = {
                "Employee_id": Employee_id,
                //"Beneficiary_id": Beneficiary_id,
                "PrimaryBeneficiary": PrimaryBeneficiary,
                "ContingentBeneficiary": ContingentBeneficiary,
                "FirstName": FirstName,
                "LastName": LastName,
                "SSN": SSN,
                "RelationshipToEmployee": RelationshipToEmployee,
                "DateOfBirth": DateOfBirth,
                "PhoneNumber": PhoneNumber,
                "PercentageOfBenefits": PercentageOfBenefits,
                "MailingAddress": MailingAddress,
                "City": City,
                "State": State,
                "ZipCode": ZipCode,
            }

            var ret = postData('/Life_Insurance/AddBeneficiaryUpdate', data)
                .then(data => {
                    console.log(data);
                    FirstStep(data);
                })
                .catch(error => console.error(error))

            //fetch('AddBeneficiaryUpdate', {
            //    body: JSON.stringify(data), //must match 'Content-Type' header
            //    cache: 'no-cache', //*default, no-cache, reload, force-cache, only-if-cached
            //    credentials: 'same-origin', //include, same-origin, *omit
            //    headers: {
            //        'Accept': 'application/json',
            //        'user-agent': 'Mozilla/4.0 MDN Example',
            //        'content-type': 'application/json'
            //    },
            //    method: 'Post', //*GET, POST, PUT, DELETE, etc...
            //    mode: 'same-origin', //no-cors, cors, *same-origin
            //    redirect: 'follow', //manual, *follow, error
            //    referrer: 'no-referrer', //*client, no-referrer
            //}).then(res => res.json())
            //    //.then(response => console.log('Success:', JSON.stringify(response)))
            //    .then(response => FirstStep(response))
            //    .catch(error => console.error('Error:', error));
        })

    })

    function FirstStep(emp) {
        Employee_id = emp.data;
    }

    function postData(url, data) {
        //Default options are marked with *
        console.log(data);
        console.log(JSON.stringify(data));
        return fetch(url, {
            body: JSON.stringify(data), //must match 'Content-Type' header
            cache: 'no-cache', //*default, no-cache, reload, force-cache, only-if-cached
            credentials: 'same-origin', //include, same-origin, *omit
            headers: {
                'Accept': 'application/json',
                'user-agent': 'Mozilla/4.0 MDN Example',
                'content-type': 'application/json'
            },
            method: 'Post', //*GET, POST, PUT, DELETE, etc...
            mode: 'same-origin', //no-cors, cors, *same-origin
            redirect: 'follow', //manual, *follow, error
            referrer: 'no-referrer', //*client, no-referrer
        }).then(res => res.json())
            .then(response => console.log('Success:', JSON.stringify(response)))
            .catch(error => console.error('Error:', error));
        //.then(Response => {
        //    console.log(Response);
        //    Response.json();
        //}) //parses response to JSON
    }
</script>