WatsonTruckV2/Models/EditUserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace WatsonTruckV2.Models
{
    public class EditUserViewModel
    {
        public EditUserViewModel()
        {
            Claims = new List<string>(); /*Roles = new List<string>();*/
        }


        public string Id { get; set; }

        [Required]
        public string UserName { get; set; }

        [Required(AllowEmptyStrings = false)]
        [Display(Name = "Email")]
        [EmailAddress]
        public string Email { get; set; }

        public List<string> Claims { get; set; }

        public IEnumerable<SelectListItem> Roles { get; set; }
        //public List<string> Roles { get; set; }



    }
}

WatsonTruckV2/Controllers/AdminUsersController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Data.Entity;
using System;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.Validation;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.UI;
using System.Web.UI.WebControls;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Text;
using System.Data;
using System.Net.Http;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Web.Mvc;
using WatsonTruckV2.Models;

namespace WatsonTruckV2.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class AdminUsersController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private ApplicationDbContext context = new ApplicationDbContext();

        public AdminUsersController()
        {
       
        }

        public AdminUsersController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
            context = new ApplicationDbContext();
        }


        //====================================
        // GET: Index 
        //==================================== 

        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var roles = context.Roles.ToList();
            return View(roles);
        }

        public bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = userManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Employee")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        //====================================
        // GET: AdminUsers/ListUsers 
        //==================================== 
        [HttpGet]
        public ActionResult ListUsers()
        {
            var userList = userManager.Users;

            return View(userList);
        }

        //====================================
        // GET: AdminUsers/CreateUser 
        //====================================  
        [HttpGet]
        public ActionResult CreateUser()
        {
            return View();
        }

        //====================================
        // Post: AdminUsers/CreateUser 
        //==================================== 
        [HttpPost]
        public async Task<ActionResult> CreateUser(UserRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                ApplicationUser applicationUser = new ApplicationUser
                {
                    UserName = model.UserName
                };

                IdentityResult result = await userManager.CreateAsync(applicationUser);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListUsers");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", result.Errors.First());
                        //var errors = string.Join(",", result.Errors);
                        //ModelState.AddModelError("", errors);
                    }
                    return View(model);
                }

            }

            return View(model);
        }

        //====================================
        // GET: AdminUsers/EditUser 
        //==================================== 
        [HttpGet]
        public async Task<ActionResult> EditUser(string Id)
        {
            if (Id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = await userManager.FindByIdAsync(Id);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {Id} cannot be found";
                return View("NotFound");
                //return HttpNotFound();
            }

            //var userClaims = await userManager.GetClaimsAsync(user.Id);
            var userRoles = await userManager.GetRolesAsync(user.Id);

            var model = new EditUserViewModel()
            {
                Id = user.Id,
                UserName = user.UserName,
                Email = user.Email,
                //Claims = userClaims.Select(c => c.Value).ToList(),
                //Roles = userRoles
            };

            return View(model);
        }


        //====================================
        // Post: AdminUsers/EditUser 
        //==================================== 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditUser([Bind(Include = "Id,UserName,Email")] EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userManager.FindByIdAsync(model.Id);
                if (user == null)
                {
                    ViewBag.ErrorMessage = $"Role with Id = {model.Id} cannot be found";
                    return View("NotFound");
                }
                else
                {
                    user.Id = model.Id;
                    user.UserName = model.UserName;
                    user.Email = model.Email;

                    var applicationUser = await userManager.FindByIdAsync(User.Identity.GetUserId());

                    var result = await userManager.UpdateAsync(applicationUser);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListUsers");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError(string.Empty, result.Errors.First());

                    }
                    return View(model);
                }
            }
            return View(model);
        }

        [HttpGet]
        public async Task<ActionResult> ManageUserRoles(string userId)
        {
            ViewBag.userId = userId;

            if (userId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id = {userId} cannot be found";
                return View("NotFound");
                //return HttpNotFound();
            }

            var model = new List<UserRoleViewModel>();

            foreach(var role in roleManager.Roles)
            {
                var UserRoleViewModel = new UserRoleViewModel
                {
                    RoleId = role.Id,
                    RoleName = role.Name
                };

                if(await userManager.IsInRoleAsync(user.Id, role.Name))
                {
                    UserRoleViewModel.isSelected = true;
                }
                else
                {
                    UserRoleViewModel.isSelected = false;
                }

                model.Add(UserRoleViewModel);

            }
  
            return View(model);
        }

        //issue with  await userManager.AddToRoleAsync 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ManageUserRoles(List<UserRoleViewModel> model, string userId, params string[] selectedRoles)
        {

            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {userId} cannot be found";
                return View("NotFound");
            }

            var userRoles = await userManager.GetRolesAsync(user.Id);

            selectedRoles = selectedRoles ?? new string[] { };

            var result = await userManager.AddToRolesAsync(user.Id, selectedRoles.Except(userRoles).ToArray<string>());
            for (int i = 0; i < model.Count;)
            {
                //replace UserName with UserRole or Name
                if (model[i].isSelected && await userManager.IsInRoleAsync(user.Id, user.UserName))
                {
                    //replace UserName with UserRole or Name
                    result = await userManager.RemoveFromRolesAsync(user.Id, user.UserName);

                }
                //replace UserName with UserRole or Name
                else if (!model[i].isSelected && await userManager.IsInRoleAsync(user.Id, user.UserName))
                {
                    //replace UserName with UserRole or Name
                    result = await userManager.RemoveFromRoleAsync(user.Id, user.UserName);
                }

                if (!result.Succeeded)
                {

WatsonTruckV2/Views/AdminUsers/CreateUser.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CreateUser</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WatsonTruckV2/Views/AdminUsers/DeleteUser.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DeleteUser</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

WatsonTruckV2/Views/AdminUsers/EditUser.cshtml
@model WatsonTruckV2.Models.EditUserViewModel
@{
    ViewBag.Title = "Edit User";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<h2>Edit User</h2>

@using (Html.BeginForm("EditUser", "AdminUsers", FormMethod.Post, new { @class = "form-horizontal", user = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.Id)
    <div class="form-group row">
        @Html.LabelFor(m => m.Id, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Id, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group row">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
        </div>
    </div>
    @*<div class="form-group">
        @Html.Label("Roles", new { @class = "control-label col-md-2" })
        <span class=" col-md-10">
            @foreach (var item in Model.Roles)
            {
                <input type="checkbox" name="Role" value="@item.Value" checked="@item.Selected" class="checkbox-inline" />
                @Html.Label(item.Value, new { @class = "control-label" })
            }
        </span>
    </div>*@
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" value="Update" class="btn btn-primary" />
            <button type="button" onclick="return Cancel()" class="btn btn-primary">Cancel</button>
        </div>
    </div>

    <div class="card">
        <div class="card-header">
            <h3>User Roles</h3>
        </div>
        <div class="card-body">
            @if (Model.Roles.Any())
            {
                foreach (var role in Model.Roles)
                {
                    <h5 class="card-title">@role</h5>
                }
            }
            else
            {
                <h5 class="card-title">None at the moment</h5>
            }
            <div class="card-footer">
                <input type="button" value="Manage Roles" onclick="location.href='@Url.Action("ManageUserRoles", "AdminUsers", new { Id = Model.Id })'" />
                @*<a class="btn btn-primary" onclick="return EditUsersInRole()" style="width:auto">Add or Remove users</a>*@
                @Html.ActionLink("Manage Roles", "ManageUserRoles", "AdminRoles", new { Id = Model.Id }, null)
            </div>
        </div>
        @* <div class="card-header">
                <h3>User Claims</h3>
            </div>
            <div class="card-body">
                @if (Model.Claims.Any())
                {
                    foreach (var claims in Model.Claims)
                    {
                        <h5 class="card-title">@claims</h5>
                    }
                }
                else
                {
                    <h5 class="card-title">None at the moment</h5>
                }
            </div>
            }*@
        @*<div class="card-footer">*@
        @*<input type="button" value="Manage Claims" onclick="location.href='@Url.Action("EditUser", "AdminUsers", new { Id = Model.Id })'" />*@
        @*<a class="btn btn-primary" onclick="return EditUsersInRole()" style="width:auto">Add or Remove users</a>*@
        @*@Html.ActionLink("ManageClaims", "EditUsersInRole", "AdminRoles", new { Id = Model.Id }, null)*@
        @*</div>*@
    </div>

}


    <script>
        function Cancel() {
            window.location.href = "/AdminUsers/ListUsers";
        }
    </script>

WatsonTruckV2/Views/AdminUsers/Index.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @if (ViewBag.displayMenu == "Yes")
        {
            <h2>Welcome Admin-<strong>@ViewBag.Name</strong>!</h2>
            <h4>
                Please click @Html.ActionLink("Home Page", "AdminRoles", "Index") to continue.
            </h4>
        }
        else
        {
            <h2>Welcome <strong>@ViewBag.Name</strong></h2>
            <h4>
                Please click @Html.ActionLink("Employee Overview", "Employee", "EmpOverview") to continue.
            </h4>
        }
    </div>
</body>
</html>

WatsonTruckV2/Views/AdminUsers/ListUsers.cshtml
@model IEnumerable<WatsonTruckV2.Models.ApplicationUser>

@{
    ViewBag.Title = "All Users";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>List Users</title>
</head>
@using (Html.BeginForm("ListUsers", "AdminUsers", FormMethod.Post, new { @class = "form-horizontal", user = "form" }))
{
    @Html.AntiForgeryToken()
    <body>
        <div>
            @if (Model.Any())
            {
                <a class="btn btn-primary" style="width:auto">
                    @Html.ActionLink("Add New User", "Register", "Account")
                </a>

                foreach (var user in Model)
                {
                    <div class="card mb-3">
                        <div class="card-header">
                            User Id: @user.Id
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">@user.UserName</h5>
                        </div>
                         <div class="card-body">
                            <h5 class="card-title">@*@user.EmployeeNumber*@</h5>
                        </div>
                         <div class="card-body">
                            <h5 class="card-title">@user.Email</h5>
                        </div>

                        <div class="card-footer">
                            <form action="DeleteUser" id="@user.Id" method="post">
                                @Html.ActionLink("Edit", "EditUser", "AdminUsers", new { UserId = user.Id }, null)
                                @*<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete user @user.UserName')">Delete  </button>*@
                                       
                                <span id="confirmDeleteSpan_@user.Id" style="display: none;">
                                    <span>Are you sure you want to delete?</span>
                                    <button type="submit" class="btn btn-danger">Yes</button>
                                    <a href="#" class="btn btn-primary" onclick="ConfirmDelete('@user.Id', false">No</a>
                                </span>
                                <span id="deleteSpan_@user.Id">
                                    <a href="#" class="btn btn-danger" onclick="ConfirmDelete('@user.Id', true)">Delete</a>
                                </span>
                            </form>
                        </div>
                    </div>
                }
            }
            else
            {
                <div class="card">
                    <div class="card-header">
                        No users created yet
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            Use the button below to create a user
                        </h5>
                    </div>
                </div>
            }
        </div>
    </body>
}
</html>

<script>
    function ConfirmDelete(id, isDeleteClicked) {
        var deleteSpan = 'deleteSpan_' + id;
        var confirmDeleteSpan = 'confirmDeletespan_' + id;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();

        }
        else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
    }
</script>

WatsonTruckV2/Views/AdminUsers/ManageUserRoles.cshtml
@model List<WatsonTruckV2.Models.UserRoleViewModel>
@{
    var userId = ViewBag.userId;
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<h2>Manage User Role</h2>

@using (Html.BeginForm("ManageUserRoles", "AdminUsers", FormMethod.Post, new { @class = "form-horizontal", user = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true)
    <div class="card">
        <div class="card-header">
            <h3>Manager User Roles</h3>
        </div>
        <div class="card-body">
            @*@foreach (var role in Model)
            {
                <div class="form-check col-md-2">
                    <input type="hidden" id="@role.RoleId" name="@role.RoleId" />
                    <input type="hidden" id="@role.RoleName" name="@role.RoleName" />
                    <input class="form-check-input" id="@role.isSelected" name="@role.isSelected" />
                    <label class="form-check-label" for="@role.isSelected">
                        @role.RoleName
                    </label>
                </div>
            }*@
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check col-md-2">
                    <input type="hidden" class="" id="@Model[i].RoleId" name="@Model[i].RoleId" />
                    <input type="hidden" class="" id="@Model[i].RoleName" name="@Model[i].RoleName" />
                    <input class="form-check-input" id="@Model[i].isSelected" name="@Model[i].isSelected" />
                    <label class="form-check-label" for="@Model[i].isSelected">
                        @Model[i].RoleName
                    </label>
                </div>
            }

            <div class="card-footer">
                <input type="submit" value="Update" id="@ViewBag.userId" onclick="location.href='@Url.Action("ManageUserRoles", "AdminUsers", new { })'" />
                @*<button type="button" id="@ViewBag.userId" onclick="return Cancel()">Cancel</button>*@
                @Html.ActionLink("Edit User", "EditUser", "AdminUsers", new { }, null)
            </div>
        </div>
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function Cancel() {
        window.location.href = "/AdminUser/EditUser";
    }
</script>