WatsonTruckV2/Models/CreateRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WatsonTruckV2.Models
{
    public class CreateRoleViewModel
    {
        [Required]
        public string UserRole { get; set; }
        public string RoleId { get; set; }
        public string Name { get; set; }
    }
}

WatsonTruckV2/Models/EditRoleViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WatsonTruckV2.Models
{
    public class EditRoleViewModel
    {
        public EditRoleViewModel()
        {
            Users = new List<string>();
        }

        public string RoleId { get; set; }

        [Required(ErrorMessage = "User Role is required")]
        public string UserRole { get; set; }

        public List<string> Users { get; set; }
        public string Name { get; set; }
    }
}

WatsonTruckV2/Controllers/AdminRolesController.cs
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Data.Entity;
using System;
using System.Diagnostics;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.ModelConfiguration;
using System.Data.Entity.ModelConfiguration.Configuration;
using System.Data.Entity.Validation;
using System.Globalization;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.UI;
using System.Web.UI.WebControls;
using Newtonsoft.Json;
using System.IO;
using System.Net;
using System.Text;
using System.Data;
using System.Net.Http;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Web.Mvc;
using WatsonTruckV2.Models;

namespace WatsonTruckV2.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class AdminRolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<ApplicationUser> userManager;
        private ApplicationDbContext context = new ApplicationDbContext();

        public AdminRolesController()
        {

        }
       

        public AdminRolesController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        //====================================
        // GET: Index 
        //==================================== 

        //public ActionResult Index()
        //{
        //    return View();
        //}

        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ViewBag.Name = user.Name;

                ViewBag.displayMenu = "No";

                if (isAdminUser())
                {
                    ViewBag.displayMenu = "Yes";
                }
                return View();
            }
            else
            {
                ViewBag.Name = "Not Logged IN";
            }
            return View();

        }

        public bool isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }

        //====================================
        // GET: ListRoles 
        //==================================== 
        [HttpGet]
        public ActionResult ListRoles()
        {
            var roleList = roleManager.Roles;

            return View(roleList);
        }

        //====================================
        // GET: CreateRole 
        //====================================  
        [HttpGet]
        public ActionResult CreateRole()
        {
            return View();
        }

        //====================================
        // Post: CreateRole 
        //==================================== 
        [HttpPost]
        public async Task<ActionResult> CreateRole(CreateRoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                IdentityRole identityRole = new IdentityRole
                {
                    Name = model.UserRole
                };

                IdentityResult result = await roleManager.CreateAsync(identityRole);

                if (result.Succeeded)
                {
                    return RedirectToAction("ListRoles");
                }
                else
                {
                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", result.Errors.First());
                        //var errors = string.Join(",", result.Errors);
                        //ModelState.AddModelError("", errors);
                    }
                    return View(model);
                }

            }

            return View(model);
        }

        //====================================
        // GET: EditRole 
        //==================================== 
        public async Task<ActionResult> EditRole(string RoleId)
        {
            if (RoleId == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var role = await roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {RoleId} cannot be found";
                return View("NotFound");
                //return HttpNotFound();
            }

            EditRoleViewModel editRoleViewModel = new EditRoleViewModel
            {
                RoleId = role.Id,
                UserRole = role.Name
            };

            foreach (var user in userManager.Users)
            {
                if (await userManager.IsInRoleAsync(role.Id, role.Name))
                {
                    editRoleViewModel.Users.Add(user.UserName);
                }
            }

            return View(editRoleViewModel);
        }


        //====================================
        // Post: EditRole 
        //==================================== 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditRole([Bind(Include = "Name,RoleId")] EditRoleViewModel editRoleViewModel)
        {
            if (ModelState.IsValid)
            {
                var role = await roleManager.FindByIdAsync(editRoleViewModel.RoleId);

                if (role == null)
                {
                    ViewBag.ErrorMessage = $"Role with Id = {editRoleViewModel.RoleId} cannot be found";
                    return View("NotFound");
                }
                else
                {
                    role.Name = editRoleViewModel.UserRole;
                    var result = await roleManager.UpdateAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("ListRoles");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", result.Errors.First());

                    }
                    return View(editRoleViewModel);
                }
            }
            return View(editRoleViewModel);
        }

        //====================================
        // GET: EditUsersInRole 
        //==================================== 
        [HttpGet]
        public async Task<ActionResult> EditUsersInRole(string RoleId)
        {
            ViewBag.RoleId = RoleId;
            //ViewBag.userId = userId;

            var role = await roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {RoleId} cannot be found";
                return View("NotFound");
                //return HttpNotFound();
            }

            var model = new List<UserRoleViewModel>();

            foreach (var user in userManager.Users)
            {
                var userRoleViewModel = new UserRoleViewModel
                {
                    userId = user.Id,
                    UserName = user.UserName

                };

                if (await userManager.IsInRoleAsync(role.Id, role.Name))
                {
                    userRoleViewModel.isSelected = true;
                }
                else
                {
                    userRoleViewModel.isSelected = false;
                }

                model.Add(userRoleViewModel);
            }

            return View(model);
        }

        //====================================
        // Post: EditUsersInRole 
        //==================================== 
        [HttpPost]
        public async Task<ActionResult> EditUsersInRole(List<UserRoleViewModel> model, string RoleId)
        {
            var role = await roleManager.FindByIdAsync(RoleId);
            if (role == null)
            {
                ViewBag.ErrorMessage = $"Role with Id = {RoleId} cannot be found";
                return View("NotFound");
                //return HttpNotFound();
            }

            for (int i = 0; i < model.Count; i++)
            {
                var user = await userManager.FindByIdAsync(model[i].userId);

                IdentityResult result = null;

                if (model[i].isSelected && !(await userManager.IsInRoleAsync(role.Id, role.Name)))
                {
                    result = await userManager.AddToRoleAsync(role.Id, role.Name);

                }
                else if (!model[i].isSelected && await userManager.IsInRoleAsync(role.Id, role.Name))
                {
                    result = await userManager.RemoveFromRoleAsync(role.Id, role.Name);
                }
                else
                {
                    continue;
                }

                if (result.Succeeded)
                {
                    if (i < (model.Count - 1))
                        continue;
                    else
                        return RedirectToAction("EditRole", new { Id = RoleId });
                }
            }

            return RedirectToAction("EditRole", new { Id = RoleId });
        }

        //====================================
        // Get: AdminRoles/DeleteRole/RoleId
        //==================================== 
        public async Task<ActionResult> DeleteRole(string RoleId)
        {

WatsonTruckV2/Views/AdminRoles/CreateRole.cshtml
@model WatsonTruckV2.Models.CreateRoleViewModel
@{
    ViewBag.Title = "Create New Role";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<h2>Create New Role</h2>

@using (Html.BeginForm("CreateRole", "AdminRoles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true)
    <div class="form-group">
        @Html.LabelFor(m => m.UserRole, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserRole, new { @class = "form-control" })
            @*@Html.DropDownList("UserRoles", (SelectList)ViewBag.Name, " ", new { @class = "form-control" })*@
        </div>
    </div>

    @*<div class="form-group">
            @Html.Label("User Role", new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.DropDownList("UserRoles", (SelectList)ViewBag.Name, " ", new { @class = "form-control" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(m => m.EmployeeNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.EmployeeNumber, new { @class = "form-control" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Create Role" />
        </div>
    </div>
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WatsonTruckV2/Views/AdminRoles/DeleteRole.cshtml
@model WatsonTruckV2.Models.CreateRoleViewModel
@*@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>*@
@{
    ViewBag.Title = "DeleteRole";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RoleId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RoleId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserRole)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserRole)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WatsonTruckV2/Views/AdminRoles/EditRole.cshtml
@model WatsonTruckV2.Models.EditRoleViewModel
@{
    ViewBag.Title = "Edit Role";
}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<h2>Edit Role</h2>

@using (Html.BeginForm("EditRole", "AdminRoles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(true)
    @Html.HiddenFor(model => model.RoleId)

    <div class="form-group">
        @Html.LabelFor(m => m.RoleId, new { @class = "col-md-2 control-label" })
        <div class="col-md-10" disabled>
            @Html.TextBoxFor(m => m.RoleId, new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(m => m.UserRole, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.UserRole, new { @class = "form-control" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.UserName, new { @class = "form-control" })
            </div>
        </div>*@

    @*<div class="form-group">
            @Html.LabelFor(m => m.EmployeeNumber, new { @class = "col-md-2 control-label" })
            <div class="col-md-10">
                @Html.TextBoxFor(m => m.EmployeeNumber, new { @class = "form-control" })
            </div>
        </div>*@

    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" value="Update" class="btn btn-primary" />
            <button type="button" onclick="return Cancel()" class="btn btn-primary">Cancel</button>
        </div>
    </div>
}
<div class="card">
    <div class="card-header">
        <h3>Users in this role</h3>
    </div>
    <div class="card-body">
        @if (Model.Users.Any())
        {
            foreach (var user in Model.Users)
            {
                <h5 class="card-title">@user</h5>
            }
        }
        else
        {
            <h5 class="card-title">None at the moment</h5>
        }
    </div>

    <div class="card-footer">
        <input type="button" value="Add or Remove users" onclick="location.href='@Url.Action("EditUsersInRole", "Admin", new { RoleId = Model.RoleId })'" />
        @*<a class="btn btn-primary" onclick="return EditUsersInRole()" style="width:auto">Add or Remove users</a>*@
        @Html.ActionLink("EditUsersInRole", "EditUsersInRole", "AdminRoles", new { RoleId = Model.RoleId }, null)
    </div>
</div>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    function Cancel() {
        window.location.href = "/AdminRoles/EditUsersInRole";
    }
</script>

WatsonTruckV2/Views/AdminRoles/EditUsersInRole.cshtml
@model List<WatsonTruckV2.Models.UserRoleViewModel>
@{
    var RoleId = ViewBag.RoleId;
    var userId = ViewBag.userId;
}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>

@using (Html.BeginForm("EditUsersInRole", "AdminRoles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary(false, "", new { @class = "text-danger" })
    <div class="card">
        <div class="card-header">
            <h3>Add or remove users from this role</h3>
        </div>
        <div class="card-body">
            @for (int i = 0; i < Model.Count; i++)
            {
                <div class="form-check-input">
                    <input type="hidden" value="@Model[i].userId" />
                    <input type="hidden" value="@Model[i].UserName" />
                    <input type="checkbox" class="checkbox-inline" id="@Model[i].isSelected" value="@Model[i].isSelected" />
                    <label class="form-check-label" for="@Model[i].UserName">@Model[i].UserName</label>
                </div>
            }
        </div>

        <div class="card-footer">
            <input type="submit" value="Update" id="@ViewBag.RoleId" style="width:auto" />
            @*<button type="button" id="@ViewBag.userId" onclick="return Cancel()">Cancel</button>*@
            @Html.ActionLink("Cancel", "EditRole", "AdminRoles", new { RoleId = RoleId }, null)
        </div>
    </div>
}

WatsonTruckV2/Views/AdminRoles/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

@if (ViewBag.displayMenu == "Yes")
{
    <h2>Welcome Admin-<strong>@ViewBag.Name</strong>!</h2>
    <h4>
        To continue to Employee Overview, click the button below.
    </h4>
    <div class="form-group">
        <div class="col-md-2">
            @Html.ActionLink("Employee Overview", "Admin", "EmpOverview")
        </div>
    </div>
}
else
{
    <h2>Welcome <strong>@ViewBag.Name</strong></h2>
    <h4>
        To continue to Employee Overview, click the button below.
    </h4>
    <div class="form-group">
        <div class="col-md-2">
            @Html.ActionLink("Employee Overview", "Employee", "EmpOverview")
        </div>
    </div>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditRole", new { id = item.Id }) |
                @Html.ActionLink("Details", "RoleDetails", new { id = item.Id }) |
                @Html.ActionLink("Delete", "DeleteRole", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<div class="form-group">
    <div class="col-md-2">
        <button onclick="return CreateRole()" class="btn">Create Role</button>
        <button onclick="return ListRoles()" class="btn">List Roles</button>
    </div>
</div>

<script>
    function CreateRole() {
        window.location.href = "/AdminRoles/CreateRole";

    }

    function ListRoles() {
        window.location.href = "/AdminRoles/ListRoles";

    }
</script>
@*<p>
        @Html.ActionLink("Create Role", "CreateRole", "Admin")
    </p>*@

WatsonTruckV2/Views/AdminRoles/ListRoles.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>

@{
    ViewBag.Title = "All Roles";
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <title>List Roles</title>
</head>
@using (Html.BeginForm("ListRoles", "AdminRoles", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <body>
        <div>
            @if (Model.Any())
            {
                foreach (var role in Model)
                {
                <div class="card mb-3">
                    <div class="card-header">
                        Role Id: @role.Id
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">@role.Name</h5>
                    </div>
                    <div class="card-footer">
                        <form action="DeleteRole" id="@role.Id" method="post">
                            @Html.ActionLink("Edit", "EditRole", "AdminRoles", new { UserId = role.Id }, null)
                            @*<button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you wan to delete role @role.Name)">Delete</button>*@

                            <span id="confirmDeleteSpan_@role.Id" style="display: none;">
                                <span>Are you sure you want to delete?</span>
                                <button type="submit" class="btn btn-danger">Yes</button>
                                <a href="#" class="btn btn-primary" onclick="ConfirmDelete('@role.Id', false)">No</a>
                            </span>
                            <span id="deleteSpan_@role.Id">
                                <a href="#" class="btn btn-danger" onclick="ConfirmDelete('@role.Id', true)">Delete</a>
                            </span>
                        </form>
                    </div>
                </div>
                }
            }
            else
            {
                <div class="card">
                    <div class="card-header">
                        No roles created yet
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">
                            Use the button below to create a role
                        </h5>
                        <button class="btn btn-primary" onclick="return CreateRole()" style="width:auto;">Create Role</button>
                    </div>
                </div>

            }
        </div>
    </body>
}
</html>

<script>
    function ConfirmDelete(id, isDeleteClicked) {
        var confirmDeleteSpan = 'confirmDeleteSpan_' + id;
        var deleteSpan = 'deleteSpan_' + id;

        if (isDeleteClicked) {
            $('#' + deleteSpan).hide();
            $('#' + confirmDeleteSpan).show();

        }
        else {
            $('#' + deleteSpan).show();
            $('#' + confirmDeleteSpan).hide();
        }
      
    }

    function CreateRole() {
        window.location.href = "/AdminRoles/CreateRole";
    }
</script>